### PR TITLE
Use JsValue as return value for ThemeColors getter

### PR DESCRIPTION
**Pull request by flosse**
Motivated by https://github.com/web-extensions-rs/web-extensions-sys/pull/2#discussion_r919144062 this might be a solution?

### CODE REVIEW

**Comment by flosse** [comment]
@Pauan would you mind to look at this?

**Comment by Pauan** [comment]
Why should it return `JsValue`? Isn't it better to have it return a more specific and useful Rust type?

**Comment by Pauan** [comment]
Ah, I see, it's because you want to support RGB arrays. Using `JsValue` is fine, as long as a higher layer wraps it to give it a more idiomatic Rust type.

**Comment by Pauan** [comment]
If you choose to use `JsValue` then you'll have to do some runtime checks for the various types:

```rust
value.is_null()                    // Checks for null
value.as_string()                  // Converts to String
value.dyn_into::<js_sys::Array>()  // Converts to Array
```

So something like this would work for a high level wrapper:

```rust
#[derive(Debug)]
pub struct Color {
    value: JsValue,
}

impl Color {
    pub fn from_str(color: &str) -> Self {
        Self { value: color.into() }
    }

    pub fn from_rgb(array: [u8; 3]) -> Self {
        Self::from_str(&format!("rgb({}, {}, {})",
            array[0] as f64 / 255.0,
            array[1] as f64 / 255.0,
            array[2] as f64 / 255.0,
        ))
    }

    // Alternative implementation which doesn't convert into a string
    pub fn from_rgb(array: [u8; 3]) -> Self {
        let value = Array::of_3(
            &JsValue::from(array[0]),
            &JsValue::from(array[1]),
            &JsValue::from(array[2]),
        ).into();

        Self { value }
    }

    pub fn as_string(&self) -> Option<String> {
        if let Some(string) = self.value.as_string() {
            Some(string)

        // Convert RGB Array into String
        } else if let Some(array) = self.value.dyn_ref::<Array>() {
            let r = array.get(0).as_f64()?;
            let g = array.get(1).as_f64()?;
            let b = array.get(2).as_f64()?;
            Some(format!("rgb({}, {}, {})", r / 255.0, g / 255.0, b / 255.0))

        } else {
            None
        }
    }
}
```

**Comment by Pauan** [comment]
Actually, instead of using a higher wrapper, you can just define `Color` like this:

```rust
use wasm_bindgen::{JsValue, JsCast};
use js_sys::Array;

#[wasm_bindgen]
extern "C" {
    #[derive(Debug)]
    pub type Color;
}

impl Color {
    pub fn from_str(color: &str) -> Self {
        JsValue::from(color).unchecked_into()
    }

    pub fn from_rgb(array: [u8; 3]) -> Self {
        Array::of3(
            &JsValue::from(array[0]),
            &JsValue::from(array[1]),
            &JsValue::from(array[2]),
        ).unchecked_into()
    }

    pub fn as_string(&self) -> Option<String> {
        if let Some(string) = self.unchecked_ref::<JsValue>().as_string() {
            Some(string)

        // Convert RGB Array into String
        } else if let Some(array) = self.dyn_ref::<Array>() {
            let r = array.get(0).as_f64()?;
            let g = array.get(1).as_f64()?;
            let b = array.get(2).as_f64()?;
            Some(format!("rgb({}, {}, {})", r / 255.0, g / 255.0, b / 255.0))

        } else {
            None
        }
    }

    fn as_u8(value: JsValue) -> Option<u8> {
        let float = value.as_f64()?;

        if float.fract() == 0.0 && float >= 0.0 && float <= 255.0 {
            Some(float as u8)

        } else {
            None
        }
    }

    pub fn as_rgb(&self) -> Option<[u8; 3]> {
        if let Some(array) = self.dyn_ref::<Array>() {
            let r = Self::as_u8(array.get(0))?;
            let g = Self::as_u8(array.get(1))?;
            let b = Self::as_u8(array.get(2))?;
            Some([r, g, b])

        } else {
            None
        }
    }
}
```

And now it can return `Color` instead of `JsValue`.

**Comment by flosse** [comment]
@Pauan your solution is really nice! I'll move it into the PR :smile:

**Pull request merged**
